services:
  cuda:
    image: nvidia/cuda:12.8.0-devel-ubuntu22.04    
    container_name: cuda-dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
